import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import localFont from "next/font/local";
import "./globals.css";

import TopBar from "./ui/components/TopBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`w-full h-[calc(100vh-65px)] ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppRouterCacheProvider>
          <TopBar />
          {children}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
