import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import "./globals.css";

import TopBar from "@/app/ui/components/TopBar";
import ThemeRegistry from '@/app/ui/components/ThemeRegistry';

export const metadata = {
  title: "Carpintería Mtz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="es">
        <body className={`w-full h-[calc(100vh-65px)] antialiased bg-[#003055]/5`}>
          <ThemeRegistry>
            <AppRouterCacheProvider>
              <TopBar />
              {children}
            </AppRouterCacheProvider>
          </ThemeRegistry>
        </body>
      </html>
  );
};
