import { getServerSession } from 'next-auth';
import { authOptions } from './lib/auth';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import "./globals.css";

import TopBar from "@/app/ui/components/TopBar";
import ThemeRegistry from '@/app/ui/components/ThemeRegistry';

export const metadata = {
  title: "Carpintería Mtz",
  description: "Generated by create next app",
};

import { fetchCategories } from './lib/serverAjax';

export default async function RootLayout({ children }) {

  const session = await getServerSession(authOptions);
  const categories = await fetchCategories();
  
  return (
      <html lang="es">
        <body className={`w-full h-[calc(100vh-65px)] antialiased bg-[#003055]/5`}>
          <ThemeRegistry>
            <AppRouterCacheProvider>
              <TopBar session={session} categories={categories} />
              {children}
            </AppRouterCacheProvider>
          </ThemeRegistry>
        </body>
      </html>
  );
};
